import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("React UI keeps task-first Sources wording and accessible icon controls", () => {
  const app = readFileSync("src/web/src/App.tsx", "utf8");
  const client = readFileSync("src/web/src/api/client.ts", "utf8");
  const i18n = readFileSync("src/web/src/i18n.ts", "utf8");
  const types = readFileSync("src/web/src/types.ts", "utf8");
  const ui = readFileSync("src/web/src/components/ui.tsx", "utf8");
  const css = readFileSync("src/web/src/styles/globals.css", "utf8");

  assert.match(app, /type View = "todos" \| "sources" \| "settings"/);
  assert.match(i18n, /type Locale = "zh-CN" \| "en-US"/);
  assert.match(i18n, /const defaultLocale: Locale = "zh-CN"/);
  assert.match(i18n, /actionInbox: "行动收件箱"/);
  assert.match(i18n, /language: "界面语言"/);
  assert.match(i18n, /language: "Interface language"/);
  assert.match(i18n, /todos: "待办"/);
  assert.match(i18n, /todos: "To-Do"/);
  assert.match(i18n, /sources: "来源"/);
  assert.match(i18n, /sources: "Sources"/);
  assert.match(i18n, /discovery: "路径发现"/);
  assert.match(i18n, /discovery: "Path discovery"/);
  assert.match(i18n, /discoveryDiscovered: "已自动发现"/);
  assert.match(i18n, /discoveryConfigured: "User configured"/);
  assert.match(app, /readLocale/);
  assert.match(app, /writeLocale\(locale\)/);
  assert.match(app, /onLocale/);
  assert.match(app, /aria-pressed=\{locale === option\}/);
  assert.doesNotMatch(app, />Evidence</);
  assert.match(app, /label=\{text\.refresh\}/);
  assert.match(app, /aria-label=\{text\.organizeAll\}/);
  assert.match(app, /aria-label=\{text\.organizeEmpty\}/);
  assert.match(app, /label=\{text\.openView\(text\.todos\)\}/);
  assert.match(app, /aria-label=\{label\}/);
  assert.match(app, /aria-label=\{text\.openTodoSources\(todo\.title\)\}/);
  assert.match(ui, /aria-label=\{label\}/);
  assert.match(i18n, /agent: "Agent"/);
  assert.match(app, /originLabel\(todo, locale\)/);
  assert.match(i18n, /temporarySession: "临时会话"/);
  assert.match(i18n, /temporarySession: "Temporary session"/);
  assert.match(app, /sourceFilter/);
  assert.match(i18n, /sourceFilter: "来源筛选"/);
  assert.match(i18n, /searchSources: "Search sources"/);
  assert.match(app, /sessionGroups\(filteredSessions, locale\)/);
  assert.match(app, /SESSION_GROUP_PREVIEW_LIMIT/);
  assert.match(app, /OBSERVATION_PREVIEW_LIMIT/);
  assert.match(i18n, /showAllMessages: "显示全部消息"/);
  assert.match(i18n, /loadMore: "Load more"/);
  assert.match(app, /max-h-\[calc\(100vh-220px\)\]/);
  assert.match(app, /ensureSessionLoaded/);
  assert.match(app, /scanChangedSources/);
  assert.match(i18n, /sourceScanFinished: "来源扫描完成。"/);
  assert.match(i18n, /sourceScanFailed: "Source scan failed: "/);
  assert.match(app, /startupStatusMessage/);
  assert.match(types, /discovery: Array/);
  assert.match(types, /status: "configured" \| "discovered" \| "missing"/);
  assert.match(app, /startup\?\.discovery\.length/);
  assert.match(app, /discoveryStatusLabel/);
  assert.match(app, /mergeSessions/);
  assert.match(app, /sessionId/);
  assert.match(app, /scrollIntoView/);
  assert.match(app, /todoGroups\(props\.openTodos, props\.locale\)/);
  assert.match(app, /OPEN_GROUP_PREVIEW_LIMIT/);
  assert.match(i18n, /showMore: \(count: number\) => `Show \$\{count\} more`/);
  assert.match(app, /aria-expanded=\{expanded\}/);
  assert.match(app, /originProjectLabel\(todo, locale\)/);
  assert.match(app, /originSessionLabel\(todo, locale\)/);
  assert.match(app, /sourceRailClass\(todo\.origin\?\.source\)/);
  assert.match(i18n, /completedIgnored: "已完成 \/ 已忽略"/);
  assert.match(i18n, /extraction: "抽取"/);
  assert.match(i18n, /advancedDiagnostics: "高级诊断"/);
  assert.match(app, /max=\{200\}/);
  assert.match(app, /organizeStatus\(result, locale\)/);
  assert.match(client, /userErrorText\(error, readLocale\(\)\)/);
  assert.match(client, /localizedUserFacingError/);
  assert.match(i18n, /llm_config_missing: "抽取需要先完成配置。"/);
  assert.match(i18n, /llm_config_missing: "Extraction needs setup."/);
  assert.match(i18n, /No actionable cards found in some sessions/);
  assert.match(i18n, /Some sessions could not be processed/);
  assert.match(i18n, /No Codex sessions were found in the source path/);
  assert.doesNotMatch(app, />LLM unavailable</);
  assert.match(css, /overflow-x: hidden/);
});
