import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

test("React UI keeps card-first Sources wording and accessible icon controls", () => {
  const app = readFileSync("src/web/src/App.tsx", "utf8");
  const client = readFileSync("src/web/src/api/client.ts", "utf8");
  const i18n = readFileSync("src/web/src/i18n.ts", "utf8");
  const types = readFileSync("src/web/src/types.ts", "utf8");
  const viewModel = readFileSync("src/web/src/view-model.ts", "utf8");
  const appShell = readFileSync("src/web/src/components/app-shell.tsx", "utf8");
  const todoBoard = readFileSync("src/web/src/components/todo-board.tsx", "utf8");
  const sourcesWorkspace = readFileSync("src/web/src/components/sources-workspace.tsx", "utf8");
  const observationText = readFileSync("src/web/src/components/observation-text.tsx", "utf8");
  const settingsWorkspace = readFileSync("src/web/src/components/settings-workspace.tsx", "utf8");
  const ui = readFileSync("src/web/src/components/ui.tsx", "utf8");
  const css = readFileSync("src/web/src/styles/globals.css", "utf8");
  const frontend = [app, appShell, todoBoard, sourcesWorkspace, observationText, settingsWorkspace, ui, css].join("\n");

  assert.match(viewModel, /type View = "todos" \| "sources" \| "settings"/);
  assert.match(i18n, /type Locale = "zh-CN" \| "en-US"/);
  assert.match(i18n, /const defaultLocale: Locale = "zh-CN"/);
  assert.match(i18n, /actionInbox: "收件箱卡片"/);
  assert.match(i18n, /actionInbox: "Inbox cards"/);
  assert.match(i18n, /language: "界面语言"/);
  assert.match(i18n, /language: "Interface language"/);
  assert.match(i18n, /todos: "卡片"/);
  assert.match(i18n, /todos: "Cards"/);
  assert.match(i18n, /sources: "来源"/);
  assert.match(i18n, /sources: "Sources"/);
  assert.match(i18n, /discovery: "路径发现"/);
  assert.match(i18n, /discovery: "Path discovery"/);
  assert.match(i18n, /discoveryDiscovered: "已自动发现"/);
  assert.match(i18n, /discoveryConfigured: "User configured"/);
  assert.match(app, /readLocale/);
  assert.match(app, /writeLocale\(locale\)/);
  assert.match(app, /onLocale/);
  assert.match(settingsWorkspace, /aria-pressed=\{locale === option\}/);
  assert.doesNotMatch(frontend, />Evidence</);
  assert.match(appShell, /label=\{text\.refresh\}/);
  assert.match(appShell, /aria-label=\{text\.organizeAll\}/);
  assert.match(todoBoard, /aria-label=\{text\.organizeEmpty\}/);
  assert.match(appShell, /label=\{text\.openView\(text\.todos\)\}/);
  assert.match(appShell, /aria-label=\{label\}/);
  assert.match(todoBoard, /aria-label=\{text\.openTodoSources\(todo\.title\)\}/);
  assert.match(ui, /aria-label=\{label\}/);
  assert.match(ui, /function Panel/);
  assert.match(ui, /function StatusCallout/);
  assert.match(ui, /function SegmentedFilter/);
  assert.match(i18n, /agent: "Agent"/);
  assert.doesNotMatch(todoBoard, /originLabel\(todo, locale\)/);
  assert.match(i18n, /temporarySession: "临时会话"/);
  assert.match(i18n, /temporarySession: "Temporary session"/);
  assert.match(app, /sourceFilter/);
  assert.match(i18n, /sourceFilter: "来源筛选"/);
  assert.match(sourcesWorkspace, /text\.searchSources/);
  assert.match(sourcesWorkspace, /sessionGroups\(filteredSessions, locale\)/);
  assert.match(sourcesWorkspace, /OBSERVATION_PREVIEW_LIMIT/);
  assert.match(i18n, /showAllMessages: "显示全部消息"/);
  assert.match(i18n, /loadMore: "Load more"/);
  assert.match(sourcesWorkspace, /max-h-\[calc\(100vh-220px\)\]/);
  assert.match(app, /ensureSessionLoaded/);
  assert.match(settingsWorkspace, /scanChangedSources/);
  assert.match(settingsWorkspace, /text\.cursorSource/);
  assert.match(settingsWorkspace, /clearDialogRef/);
  assert.match(settingsWorkspace, /showModal\(\)/);
  assert.match(settingsWorkspace, /text\.clearTodoCards/);
  assert.match(i18n, /clearTodoCards: "清空卡片数据库"/);
  assert.match(i18n, /clearTodoCards: "Clear card database"/);
  assert.match(i18n, /advancedLlmSettings: "高级 LLM 配置"/);
  assert.match(i18n, /advancedLlmSettings: "Advanced LLM settings"/);
  assert.match(settingsWorkspace, /text\.extractionService/);
  assert.match(settingsWorkspace, /text\.advancedLlmSettings/);
  assert.match(settingsWorkspace, /settings\.llm\.apiKeySource === "managed"/);
  assert.match(i18n, /sourceScanFinished: "来源扫描完成。"/);
  assert.match(i18n, /sourceScanFailed: "Source scan failed: "/);
  assert.match(app, /startupStatusMessage/);
  assert.match(app, /OrganizeStatus/);
  assert.match(app, /\/todos\/organize\/status/);
  assert.match(app, /setOrganizeRunning\(nextOrganizeStatus\.running\)/);
  assert.match(app, /organizeHistory=\{<OrganizeHistoryPanel/);
  assert.doesNotMatch(app, /^\s*<OrganizeHistoryPanel items=\{organizeHistory\} locale=\{locale\} \/>$/m);
  assert.match(app, /isFailedOrganizeResult\(latest\.result\)/);
  assert.match(app, /onToggle=\{\(event\) => setOpen\(event\.currentTarget\.open\)\}/);
  assert.match(todoBoard, /organizeHistory\?: ReactNode/);
  assert.match(todoBoard, /\{props\.organizeHistory\}/);
  assert.match(app, /onRestore=\{\(id\) => void updateTodo\(id, "todo"\)\}/);
  assert.match(types, /discovery: Array/);
  assert.match(types, /export type SourceKind = "codex" \| "claude-code" \| "cursor"/);
  assert.match(types, /cursor: \{ path\?: string \}/);
  assert.match(types, /Extract<SourceKind, "codex" \| "claude-code" \| "cursor">/);
  assert.match(types, /projectPath\?: string/);
  assert.match(types, /interface TaskChainView/);
  assert.match(types, /interface ChainNodeSummary/);
  assert.match(types, /chain\?: TaskChainView/);
  assert.match(types, /status: "configured" \| "discovered" \| "missing"/);
  assert.match(settingsWorkspace, /startup\?\.discovery\.length/);
  assert.match(settingsWorkspace, /discoveryStatusLabel/);
  assert.match(app, /mergeSessions/);
  assert.match(app, /sessionId/);
  assert.match(app, /scrollIntoView/);
  assert.match(app, /attempts\+\+ < 5/);
  assert.match(app, /refreshSources/);
  assert.match(app, /scanSource\("codex"\)/);
  assert.match(app, /scanSource\("claude-code"\)/);
  assert.match(app, /scanSource\("cursor"\)/);
  assert.match(todoBoard, /visibleOpenGroups/);
  assert.match(todoBoard, /projectTodoGroups\(visibleOpenTodos, props\.locale\)\.map/);
  assert.match(todoBoard, /projectTaskChains\(group\.todos\)/);
  assert.match(todoBoard, /TaskChainContainer/);
  assert.match(todoBoard, /todo\.chain\?\.completedNodes/);
  assert.match(todoBoard, /OPEN_GROUP_PREVIEW_LIMIT/);
  assert.match(todoBoard, /visibleLimit \+ OPEN_GROUP_PREVIEW_LIMIT/);
  assert.match(todoBoard, /\$\{todo\.chain\.id\}:\$\{todo\.id\}/);
  assert.match(i18n, /showMore: \(count: number\) => `Show \$\{count\} more`/);
  assert.match(i18n, /needsReview: "当前显示"/);
  assert.match(i18n, /needsReview: "Shown"/);
  assert.match(frontend, /aria-expanded=\{expanded\}/);
  assert.match(i18n, /unknownProject: "未识别项目"/);
  assert.match(i18n, /unknownProject: "Unknown project"/);
  assert.match(todoBoard, /projectSourceSummary\(group\.todos, props\.locale\)/);
  assert.match(todoBoard, /text\.projectPrefix/);
  assert.match(todoBoard, /text\.searchProjects/);
  assert.match(todoBoard, /ProjectMenuItem/);
  assert.match(todoBoard, /ClosedTodoGroup/);
  assert.match(todoBoard, /text\.completedCards/);
  assert.match(todoBoard, /text\.ignoredCards/);
  assert.match(todoBoard, /text\.restoreTodo\(todo\.title\)/);
  assert.match(todoBoard, /todoStatusBadgeClass/);
  assert.doesNotMatch(todoBoard, /ProjectChip/);
  assert.doesNotMatch(todoBoard, /key: "blocked"/);
  assert.doesNotMatch(todoBoard, /key: "in_progress"/);
  assert.doesNotMatch(todoBoard, /key: "needs_review"/);
  assert.doesNotMatch(todoBoard, /originSessionLabel\(todo, locale\)/);
  assert.match(todoBoard, /<SourceBadge todo=\{todo\} locale=\{locale\} \/>/);
  assert.doesNotMatch(todoBoard, /todoTaskSignal\(todo, locale\)/);
  assert.doesNotMatch(todoBoard, /todo\.metadata\.nextStep/);
  assert.match(todoBoard, /text\.completedChainSteps\(todo\.chain\?\.completedNodeCount \?\? completedNodes\.length\)/);
  assert.doesNotMatch(todoBoard, /completionStateLabel\(state, locale\)/);
  assert.doesNotMatch(todoBoard, /todoConfidence\(todo\)/);
  assert.doesNotMatch(todoBoard, /evidenceIds\.length \* 9/);
  assert.doesNotMatch(todoBoard, /text\.confidenceLabel/);
  assert.doesNotMatch(i18n, /confidenceLabel/);
  assert.doesNotMatch(i18n, /Confidence/);
  assert.doesNotMatch(i18n, /置信度/);
  assert.doesNotMatch(todoBoard, /taskSignal/);
  assert.match(todoBoard, /todoEventTime\(todo\)/);
  assert.match(todoBoard, /formatRelativeTime\(todoEventTime\(todo\), locale\)/);
  assert.match(todoBoard, /sortTodosByEventTime\(todos\)\.map/);
  assert.match(todoBoard, /todo\.metadata\.completionSummary &&/);
  assert.match(todoBoard, /<details/);
  assert.match(i18n, /completedChainSteps: \(count: number\) => `已完成 \$\{count\} 步`/);
  assert.match(i18n, /completedChainSteps: \(count: number\) => `\$\{count\} completed steps`/);
  assert.match(i18n, /currentChainNode: "当前节点"/);
  assert.match(i18n, /currentChainNode: "Current node"/);
  assert.match(todoBoard, /className="todo-project-section"/);
  assert.match(todoBoard, /className="todo-project-cards"/);
  assert.match(css, /\.todo-project-section/);
  assert.match(css, /\.todo-project-cards/);
  assert.match(todoBoard, /\{project\} <span aria-hidden="true">›<\/span> \{session\}/);
  assert.doesNotMatch(todoBoard, /sourceRailClass\(todo\.origin\?\.source\)/);
  assert.match(sourcesWorkspace, /sessionProjectLabel\(session, locale\)/);
  assert.match(sourcesWorkspace, /sessionProjectLabel\(selected, locale\)/);
  assert.match(sourcesWorkspace, /projectOptions/);
  assert.match(sourcesWorkspace, /matchesSessionProject/);
  assert.match(sourcesWorkspace, /text\.projectPrefix/);
  assert.match(sourcesWorkspace, /text\.searchProjects/);
  assert.match(sourcesWorkspace, /aria-label=\{expanded \? text\.collapseProject\(group\.label\) : text\.expandProject\(group\.label\)\}/);
  assert.match(sourcesWorkspace, /autoExpandedGroupKeyRef/);
  assert.match(sourcesWorkspace, /current\[group\.key\] \? current :/);
  assert.match(sourcesWorkspace, /const visibleSessions = expanded \? group\.sessions : \[\]/);
  assert.match(sourcesWorkspace, /sourceLabel\(selected\.source, locale\)\} · \{sessionProjectLabel\(selected, locale\)\}/);
  assert.match(sourcesWorkspace, /sourceLabel\(session\.source, locale\)/);
  assert.match(sourcesWorkspace, /<ObservationText observation=\{observation\}/);
  assert.match(observationText, /from "react-markdown"/);
  assert.match(observationText, /skipHtml/);
  assert.match(observationText, /isAgentContextText\(observation\.text\)/);
  assert.match(observationText, /displayAgentContextText/);
  assert.match(observationText, /displayTurnAbortedText/);
  assert.match(observationText, /attachmentMarkdownText/);
  assert.doesNotMatch(observationText, /withAttachmentToken/);
  assert.doesNotMatch(observationText, /localToken\(\)/);
  assert.match(client, /sessionStorage\.getItem\("ai-inbox-token"\)/);
  assert.doesNotMatch(client, /new URLSearchParams\(location\.hash\.replace/);
  assert.match(observationText, /sourceDisplayText\(observation\.text\)/);
  assert.doesNotMatch(observationText, /dangerouslySetInnerHTML/);
  assert.doesNotMatch(observationText, /rehype-raw/);
  assert.match(todoBoard, /row\.role === "assistant" \|\| row\.role === "user"/);
  assert.match(sourcesWorkspace, /setShowAllMessages\(true\)/);
  assert.match(sourcesWorkspace, /sourceMessageTone/);
  assert.match(sourcesWorkspace, /observation\.role === "user"\) return "ml-auto/);
  assert.doesNotMatch(sourcesWorkspace, /observation\.role === "assistant"\) return "ml-auto/);
  assert.match(sourcesWorkspace, /text\.agentContext/);
  assert.match(sourcesWorkspace, /text\.turnInterrupted/);
  assert.match(sourcesWorkspace, /isTurnAbortedText\(observation\.text\)/);
  assert.match(sourcesWorkspace, /isAgentContextText\(observation\.text\)/);
  assert.match(sourcesWorkspace, /sourceObservationTime\(observation\.createdAt\)/);
  assert.doesNotMatch(sourcesWorkspace, /new Date\(observation\.createdAt\)\.toLocaleString\(\)/);
  assert.match(css, /\.source-markdown/);
  assert.match(i18n, /completedIgnored: "已完成 \/ 已忽略"/);
  assert.match(i18n, /completedCards: "已完成"/);
  assert.match(i18n, /ignoredCards: "已忽略"/);
  assert.match(i18n, /restore: "恢复"/);
  assert.match(i18n, /restoreTodo: \(title: string\) => `恢复 \$\{title\}`/);
  assert.match(i18n, /expandProject: \(name: string\) => `展开 \$\{name\}`/);
  assert.match(i18n, /collapseProject: \(name: string\) => `收起 \$\{name\}`/);
  assert.match(i18n, /turnInterrupted: "中断事件"/);
  assert.match(i18n, /turnInterrupted: "Interrupted turn"/);
  assert.match(i18n, /happenedNow: "刚刚发生"/);
  assert.match(i18n, /happenedNow: "Happened just now"/);
  assert.match(i18n, /happenedAgo: \(value: string\) => `\$\{value\}前发生`/);
  assert.match(i18n, /happenedAgo: \(value: string\) => `Happened \$\{value\} ago`/);
  assert.match(i18n, /agentProgress: "Agent 进展"/);
  assert.match(i18n, /agentProgress: "Agent progress"/);
  assert.match(i18n, /extraction: "抽取"/);
  assert.match(i18n, /advancedDiagnostics: "高级诊断"/);
  assert.match(i18n, /advancedLlmSettings: "高级 LLM 配置"/);
  assert.match(settingsWorkspace, /md:grid-cols-2/);
  assert.match(settingsWorkspace, /max=\{200\}/);
  assert.match(app, /organizeStatus\(result, locale\)/);
  assert.match(client, /x-ai-inbox-token/);
  assert.doesNotMatch(client, /sessionStorage\.setItem\("ai-inbox-token", token\)/);
  assert.doesNotMatch(client, /history\.replaceState/);
  assert.match(client, /class ApiError extends Error/);
  assert.match(client, /status: number/);
  assert.match(client, /data: unknown/);
  assert.match(client, /userErrorText\(error, readLocale\(\)\)/);
  assert.match(client, /localizedUserFacingError/);
  assert.match(app, /error instanceof ApiError/);
  assert.match(app, /organizeResultFromError/);
  assert.match(app, /organizeFailureReasonText/);
  assert.match(app, /dedupeBatchFailures/);
  assert.match(app, /result\.details\?\.failureReason/);
  assert.match(types, /reason: string/);
  assert.match(types, /failureReason\?: string/);
  assert.match(i18n, /llm_config_missing: "抽取需要先完成配置。"/);
  assert.match(i18n, /llm_config_missing: "Extraction needs setup."/);
  assert.match(i18n, /api_key_missing/);
  assert.match(i18n, /llm_disabled/);
  assert.match(i18n, /http_401/);
  assert.match(i18n, /http_403/);
  assert.match(i18n, /http_404/);
  assert.match(i18n, /http_429/);
  assert.match(i18n, /network_error/);
  assert.match(i18n, /invalid_schema/);
  assert.match(i18n, /No actionable cards found in some sessions/);
  assert.match(i18n, /Some sessions could not be processed/);
  assert.match(i18n, /organizeHistory: "本次整理记录"/);
  assert.match(i18n, /organizeHistory: "This session’s organize history"/);
  assert.match(i18n, /organize_failed: "整理失败，详情如下。"/);
  assert.match(i18n, /organize_failed: "Organize failed\. Details below\."/);
  assert.doesNotMatch(i18n, /Open diagnostics for details/);
  assert.doesNotMatch(i18n, /打开诊断查看详情/);
  assert.match(i18n, /No Codex sessions were found in the source path/);
  assert.match(i18n, /cursor_path_not_found/);
  assert.match(i18n, /No Cursor sessions were found in the source path/);
  assert.match(i18n, /cursor: "Cursor"/);
  assert.doesNotMatch(frontend, />LLM unavailable</);
  assert.match(css, /todo-description/);
  assert.match(css, /todo-meta-row/);
  assert.match(css, /overflow-x: hidden/);
});
